.TH distcheck 1 "November 12, 2010" "Version 3.0" "USER COMMANDS"
.SH NAME
distcheck \- check installability of packages according to metadata

.SH SYNOPSIS
\fBdistcheck\fR [option] ... \fIuri\fR
.br
\fBdebcheck\fR [option] ... \fIfile\fR
.br
\fBrpmcheck\fR [option] ... \fIfile\fR
.br
\fBeclipsecheck\fR [option] ... \fIfile\fR

.SH DESCRIPTION
.B distcheck
determines, for a set of package control stanzas, called the
repository, whether packages of the repository can be installed
relative to the repository according to the inter-package
relationsships expressed in the package control stanzas. The exact set
of relevant control fields and their meaning depends on the type of the
repository.
.P
The constraint solving algorithm is complete, that is it finds a
solution whenever there exists one, even for multiple disjunctive
dependencies and deep package conflicts. This problem is
computationally infeasible in theory (that is, NP-complete), but can
be solved very efficiently for package repositories that actually ocur
in practice.

.SH INPUT SPECIFICATION
Currently supported repository types are debian, rpm, and eclipse. The
.B distcheck
tool expects its input specifiation in the form
.I type://pathname
where
.I type
is one of \fBdeb\fR, \fBrpm\fR, or \fBeclipse\fR, and
.I pathname
is the pathname of a file containing the input. The package metadata
found in that file must correspond to correspond to the
.I type
given in the URI.

When invoked as \fItype\fBcheck\fR, the type of the repository is
assumed to be \fItype\fR, and the input is simply given in form of a
pathname of a file containing the repository.
.B debcheck
accepts in addition 
.B --
as input specification, with the effect that input is taken from
standard input.	
  
.SH INPUT FORMATS

.SS Debian
The input file has to contain stanzas in the format of deb-control(5),
separated by one blank line. For instance, the Packages files as found
on a Debian mirror server, or in the directory
\fI/var/lib/apt/lists/\fR of a Debian system, are suitable as input to
\fBedos-debcheck\fR.
.P
Installability of packages is analyzed according to their
\fBDepends\fR, \fBConflicst\fR, and \fBProvides\fR fields with their
meaning as of Debian policy version 3.9.0. \fBPre-depends\fR are
treated like \fBDepends\fR, and \fBBreaks\fR are treated like
\fBConflicts\fR.
.P
In the case of Debian, it is not possible to install at the same time
two packages with the sqme name but different versions.

.SS RPM

.SS Eclipse


.SH OPTIONS
.TP
.B \-explain
Explain the results
.TP
.B \-rules
Print generated rules
.TP
.B \-failures
Only show failures
.TP
.B \-successes
Only show successes
.TP
.B \-quiet
Supress warnings and progress/timing messages
.TP
.B \-xml
Output results in XML format
.TP
.B \-help, \-\-help
Display this list of options

.SH EXIT CODE
The exit code is 0 when all packages that were asked to be checked
(either explicitly with the \-checkonly option, or because they exist
in the package pool file) are available and found to be installable,
it is 1 when a least one of these packages is available but not
installable, and it is 2 when at least one of the packages is not
available but all available packages are found to be
installable. Hence, the exit code 2 can occur only when the \-checkonly
option is used.


.SH EXAMPLE
Check which packages in a particular distribution are not installable and why:

  edos-debcheck \-failures \-explain < Packages

where Packages is the file pertaining to that distribution, as for instance
found in the directory \fI	/var/lib/apt/lists\fR.


.SH AUTHOR
The first verision of edos-debcheck had been written by Jérôme
Vouillon for the EDOS project. The current version has been rewritten
by Pietro Abate.

.SH SEE ALSO
.BR deb-control (5)

<http://www.edos-project.org> is the home page of the EDOS project.

